"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
type Mode = "login" | "register";
export function AuthForm({ mode }: { mode: Mode }) {
  const isRegister = mode === "register"; const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form.entries());
    if (isRegister && body.password !== body.confirmPassword) { setError("Passwords do not match."); return; }
    setLoading(true); try { const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data: { error?: string } = await response.json(); if (!response.ok) { setError(data.error ?? "Something went wrong."); return; } window.location.assign("/dashboard"); } catch { setError("Unable to connect. Please try again."); } finally { setLoading(false); }
  }
  return <main className="flex min-h-screen items-center justify-center bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-violet-950/40 via-slate-950 to-slate-950 px-4"><section className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900/70 p-7 shadow-2xl shadow-black/30 sm:p-9"><Link href="/" className="text-sm font-semibold tracking-wide text-violet-400">VOICE STUDIO</Link><h1 className="mt-6 text-2xl font-semibold">{isRegister ? "Create your account" : "Welcome back"}</h1><p className="mt-2 text-sm text-slate-400">{isRegister ? "Start building your voice workspace." : "Sign in to continue to your workspace."}</p><form className="mt-7 space-y-4" onSubmit={submit}>{isRegister && <Field label="Name" name="name" autoComplete="name" />}<Field label="Email" name="email" type="email" autoComplete="email" /><Field label="Password" name="password" type="password" autoComplete={isRegister ? "new-password" : "current-password"} />{isRegister && <Field label="Confirm password" name="confirmPassword" type="password" autoComplete="new-password" />}{error && <p role="alert" className="rounded-lg border border-red-900/70 bg-red-950/50 px-3 py-2 text-sm text-red-300">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-violet-500 px-4 py-2.5 font-medium text-white transition hover:bg-violet-400 disabled:cursor-not-allowed disabled:opacity-60">{loading ? "Please wait…" : isRegister ? "Create account" : "Sign in"}</button></form><p className="mt-6 text-center text-sm text-slate-400">{isRegister ? "Already have an account?" : "New to Voice Studio?"} <Link className="font-medium text-violet-400 hover:text-violet-300" href={isRegister ? "/login" : "/register"}>{isRegister ? "Sign in" : "Create one"}</Link></p></section></main>;
}
function Field({ label, name, type = "text", autoComplete }: { label: string; name: string; type?: string; autoComplete: string }) { return <label className="block text-sm font-medium text-slate-200">{label}<input className="mt-1.5" name={name} type={type} autoComplete={autoComplete} required minLength={name.includes("password") ? 8 : undefined} /></label>; }
