"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { LogoutButton } from "@/components/logout-button";
const links = [{ label: "Dashboard", href: "/dashboard", icon: "⌂" }, { label: "Text to Speech", href: "/dashboard/tts", icon: "◉" }, { label: "Voice Cloning", href: "/dashboard/clone", icon: "◌" }, { label: "Voice Design", href: "/dashboard/design", icon: "✦" }, { label: "My Voices", href: "/dashboard/voices", icon: "♫" }, { label: "History", href: "/dashboard/history", icon: "◷" }];
export function DashboardSidebar({ mobileOnly = false }: { mobileOnly?: boolean }) { const [open, setOpen] = useState(false); const path = usePathname(); const navigation = <nav className="space-y-1">{links.map((link) => { const active = path === link.href; return <Link key={link.href} href={link.href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${active ? "bg-violet-500/15 font-medium text-violet-200" : "text-slate-400 hover:bg-slate-800 hover:text-slate-100"}`}><span className="w-4 text-center">{link.icon}</span>{link.label}</Link>; })}</nav>;
  return <>{mobileOnly && <button onClick={() => setOpen(true)} aria-label="Open navigation" className="rounded-lg border border-slate-700 p-2 text-slate-300 md:hidden">☰</button>}{!mobileOnly && <aside className="hidden w-64 shrink-0 border-r border-slate-800 bg-slate-950 p-5 md:flex md:flex-col"><Brand />{navigation}<div className="mt-auto border-t border-slate-800 pt-4"><LogoutButton /></div></aside>}{open && <div className="fixed inset-0 z-50 bg-slate-950/75 backdrop-blur-sm md:hidden"><aside className="flex h-full w-72 flex-col border-r border-slate-800 bg-slate-950 p-5"><div className="flex items-center justify-between"><Brand /><button onClick={() => setOpen(false)} aria-label="Close navigation" className="rounded-lg p-2 text-slate-400 hover:bg-slate-800">×</button></div><div className="mt-7">{navigation}</div><div className="mt-auto border-t border-slate-800 pt-4"><LogoutButton /></div></aside></div>}</>; }
function Brand() { return <Link href="/dashboard" className="mb-8 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-500 font-bold text-white">V</span><span className="font-semibold tracking-tight text-white">Voice Studio</span></Link>; }
