import Link from "next/link";
import type { ReactNode } from "react";

export function PageIntro({ eyebrow, title, description, children }: { eyebrow?: string; title: string; description: string; children?: ReactNode }) { return <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="text-xs font-bold uppercase tracking-[.18em] text-violet-400">{eyebrow}</p>}<h1 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{description}</p></div>{children}</div>; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-800 bg-slate-900/65 shadow-sm shadow-black/20 ${className}`}>{children}</section>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: { label: string; href: string } }) { return <Card className="flex min-h-64 flex-col items-center justify-center px-6 py-12 text-center"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-violet-500/10 text-xl">✦</div><h2 className="mt-4 text-lg font-medium text-white">{title}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-400">{description}</p>{action && <Link href={action.href} className="mt-5 rounded-lg bg-violet-500 px-4 py-2 text-sm font-medium text-white hover:bg-violet-400">{action.label}</Link>}</Card>; }
export function StatCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card className="p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-semibold text-white">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></Card>; }
export function QuickActionCard({ title, description, href, icon }: { title: string; description: string; href: string; icon: string }) { return <Link href={href} className="group rounded-2xl border border-slate-800 bg-slate-900/65 p-5 transition hover:-translate-y-0.5 hover:border-violet-500/60 hover:bg-slate-900"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-500/10 text-lg text-violet-300">{icon}</div><h2 className="mt-5 font-medium text-white">{title}</h2><p className="mt-1.5 text-sm leading-6 text-slate-400">{description}</p><p className="mt-4 text-sm font-medium text-violet-400">Open workspace →</p></Link>; }
export function StatusBadge({ status }: { status: string }) { const colors: Record<string, string> = { pending: "bg-amber-400/10 text-amber-300", processing: "bg-sky-400/10 text-sky-300", completed: "bg-emerald-400/10 text-emerald-300", failed: "bg-red-400/10 text-red-300" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${colors[status] ?? "bg-slate-700 text-slate-300"}`}>{status}</span>; }
