import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { connectToDatabase } from "@/lib/db";
import { FishAudioError, generateSpeech } from "@/lib/fish-audio";
import { Generation } from "@/models/Generation";
import { Voice } from "@/models/Voice";
const MAX_TEXT_LENGTH = 5000;
type TtsInput = { text?: unknown; voiceId?: unknown; model?: unknown };
export async function POST(request: Request) { const user = await getCurrentUser(); if (!user) return NextResponse.json({ error: "Authentication is required." }, { status: 401 }); let generationId: string | undefined;
  try { const input = await request.json() as TtsInput; if (typeof input.text !== "string" || !input.text.trim()) return NextResponse.json({ error: "Enter text to generate speech." }, { status: 400 }); const text = input.text.trim(); if (text.length > MAX_TEXT_LENGTH) return NextResponse.json({ error: `Text must be ${MAX_TEXT_LENGTH.toLocaleString()} characters or fewer.` }, { status: 400 }); if (input.voiceId !== undefined && (typeof input.voiceId !== "string" || !/^[a-f\d]{24}$/i.test(input.voiceId))) return NextResponse.json({ error: "The selected voice is invalid." }, { status: 400 }); const configuredModel = process.env.FISH_TTS_MODEL; if (!configuredModel) return NextResponse.json({ error: "Text-to-speech is not configured on this server." }, { status: 500 }); if (input.model !== undefined && input.model !== configuredModel) return NextResponse.json({ error: "The selected model is not available." }, { status: 400 }); await connectToDatabase(); let voice: { id: string; name: string; fishReferenceId?: string } | null = null; if (typeof input.voiceId === "string") { voice = await Voice.findOne({ _id: input.voiceId, userId: user.id }).select("name fishReferenceId"); if (!voice) return NextResponse.json({ error: "That voice is unavailable." }, { status: 404 }); if (!voice.fishReferenceId) return NextResponse.json({ error: "That voice is not ready for text-to-speech." }, { status: 400 }); }
    const generation = await Generation.create({ userId: user.id, type: "tts", input: text, voiceId: voice?.id, voiceName: voice?.name, model: configuredModel, status: "processing" }); generationId = generation.id; const result = await generateSpeech({ text, model: configuredModel, referenceId: voice?.fishReferenceId }); await Generation.findByIdAndUpdate(generationId, { status: "completed" }); return new Response(result.audio, { status: 200, headers: { "Content-Type": result.contentType, "Content-Disposition": "inline; filename=voice-studio.mp3", "X-Generation-Id": generationId, "Cache-Control": "no-store" } });
  } catch (error) { if (generationId) { try { await Generation.findByIdAndUpdate(generationId, { status: "failed" }); } catch (updateError) { console.error("Could not mark generation failed", updateError); } } if (error instanceof FishAudioError) return NextResponse.json({ error: error.message }, { status: error.status }); console.error("TTS request failed", error); return NextResponse.json({ error: "Unable to generate speech. Please try again." }, { status: 500 }); }
}
