create table if not exists public.subscription_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lemonsqueezy_subscription_id text not null,
  lemonsqueezy_customer_id text,
  lemonsqueezy_variant_id text,
  subscription_interval text,
  plan text,
  status text,
  price numeric,
  currency text,
  started_at timestamptz,
  renews_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subscription_history_unique_user_subscription
    unique (user_id, lemonsqueezy_subscription_id)
);

create index if not exists subscription_history_user_id_idx
  on public.subscription_history (user_id);

create index if not exists subscription_history_user_started_at_idx
  on public.subscription_history (user_id, started_at desc);

alter table public.subscription_history enable row level security;

drop policy if exists "Users can read their own subscription history" on public.subscription_history;

create policy "Users can read their own subscription history"
  on public.subscription_history
  for select
  using (auth.uid() = user_id);
